version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: gigr-postgres
    ports:
      - 5432:5432
    volumes:
      - ./.postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=gigruser
      - POSTGRES_DB=gigrdb

  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: gigr-dynamodb
    ports:
      - 8000:8000
    environment:
      - ENV=development
    
   
