## postgresql docker compose setup
version: '3.9'

services:
  postgres:
    # django database for local development
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ./.postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=gigruser
      - POSTGRES_DB=gigrdb