name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check Out Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t deandoyle/hello-world-go:latest .
          docker push deandoyle/hello-world-go:latest

      # Step 4: Deploy to EC2
      - name: Set up SSH Key
        run: echo "${{ secrets.EC2_KEY }}" > key.pem
        
      - name: Secure SSH Key
        run: chmod 600 key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} <<EOF
          docker pull deandoyle/hello-world-go:latest
          docker stop hello-world-go || true
          docker rm hello-world-go || true
          docker run -d -p 8080:8080 --name hello-world-go deandoyle/hello-world-go:latest
          EOF

      - name: Clean up SSH Key
        run: rm -f key.pem
