name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check Out Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t deandoyle/gigr:latest .
          docker push deandoyle/gigr:latest

      # Step 4: Set up SSH Key
      - name: Set up SSH Key
        run: echo "${{ secrets.EC2_KEY }}" > key.pem

      - name: Secure SSH Key
        run: chmod 600 key.pem

      # Step 5: Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} <<EOF
          docker pull deandoyle/gigr:latest
          docker stop gigr 2>/dev/null || true
          docker rm gigr 2>/dev/null || true
          docker run -d -p 80:8080 \
            -e DB_HOST="${{ secrets.DB_HOST }}" \
            -e DB_NAME="${{ secrets.DB_NAME }}" \
            -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            -e DB_USER="${{ secrets.DB_USER }}" \
            -e AWS_REGION="${{ secrets.AWS_REGION }}" \
            -e COGNITO_CLIENT_ID="${{ secrets.COGNITO_CLIENT_ID }}" \
            -e COGNITO_USER_POOL_ID="${{ secrets.COGNITO_USER_POOL_ID }}" \
            -e DB_PORT="${{ secrets.DB_PORT }}" \
            -e DB_SSL_MODE="${{ secrets.DB_SSL_MODE }}" \
          --name gigr deandoyle/gigr:latest
          EOF

      # Step 6: Clean up SSH Key
      - name: Clean up SSH Key
        run: rm -f key.pem
